name: sor_bov

version: 0.0.1

description: Sor node

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  shelf_web_socket: ^3.0.0
  cryptography: ^2.7.0
  hive: ^2.2.3
  bs58: ^1.0.2

dev_dependencies:
  test: ^1.24.6
  hive_generator: ^2.0.1
  build_runner: ^2.5.4 # dart run build_runner build
  